# List samples here
samples:
    - Sample1
    - Sample2
    - Sample3

tests:
    - all

samples_csv:
    samples,as,a,csv,list

reference_sample: control_sample_name
min_insertion_length: 100
max_distance_to_reference_insertion: 50
min_mapq: 20
min_detected_inclusion_length: 50

base_dir:
    /your/base/project/folder/

repbase:
    ./repbase_db/permisive_rebase.fa

lastal_dir:
    /path/to/lastal

python_dir:
    /path/to/python

minimap_dir:
    /path/to/minimap2

samtools_dir:
    /path/to/samtools

base_ref:
    /path/to/GRCh38.fna

minimap2_preset:
    map-ont

lra_preset:
    ONT

meryl_dir:
   /path/to/meryl

winnow_dir:
   /path/to/winnowmap

sniffles_dir:
    /path/to/sniffles

racon_dir:
    /path/to/racon
    
somrit_dir:
    /path/to/somrit

asm_hap1:
    /path/to/asm/hap1.fa

asm_hap2:
    /path/to/asm/hap2.fa

# Reference for test. Same as base ref normally
reference_all:
    /path/to/GRCh38.fna 

insert_mapping_fraction:
    0

hc_window_size:
    100

min_mapq_fraction:
    1.0

xlarge_window:
  1000

large_window:
  500

medium_window:
  200

small_window:
  50

telomere_filter:
    utils/hg38_telomeres.tsv

centromere_filter:
    utils/hg38_centromeres.tsv

reference_tsv_to_filter:
    /path/to/control/sample/tsv
