samples:
    - combined_sample

tests:
    - all

chromosomes:
    - chr1
    - chr2
    - chr3
    - chr4
    - chr5
    - chr6
    - chr7
    - chr8
    - chr9
    - chr10
    - chr11
    - chr12
    - chr13
    - chr14
    - chr15
    - chr16
    - chr17
    - chr18
    - chr19
    - chr20
    - chr21
    - chr22
    - chrX
    - chrY


base_dir:
    /your/base/project/folder/

python_dir:
    /path/to/python

minimap_dir:
    /path/to/minimap2

samtools_dir:
    /path/to/samtools

base_ref:
    /path/to/GRCh38.fna

bed_all:
    /path/to/deleted/regions.bed 

